title: "Mouse Ear Blog"
email: "your-email@example.com"
description: >-
  Write an awesome description for your new site here.
baseurl: ""
url: "https://mouse-ear.github.io"

twitter_username: jekyllrb
github_username: jekyll

# GitHub Pages에서 원격 테마를 사용하기 위한 설정
remote_theme: mouse-ear/jekyll-theme-simplex@main

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
